security:
    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    providers:
        in_memory:
            memory:
                users:
                    mickey:
                        password: $2y$12$2UEK93WAVVZ4Hq14Q666F.K5JDyHdSxk0OLD45rHImx.1quUoOEu6
                        roles: 'ROLE_USER'
                    donald:
                        password: $2y$12$8Kx72mYU0iBwWb86DVSBsuOegOkKXq5rc03YBr3U3zW5Dst9r0RZO
                        roles: 'ROLE_USER'
                    admin:
                        password: $2y$12$AhBVcAiBamqGXqCVapYERumMtrse/6zkOV53/cN8jfZWfT/yeJ2Di
                        roles:  'ROLE_ADMIN'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: login
                check_path: login
                always_use_default_target_path: true
            logout:
                path: /logout
                target: /

            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/cookbook/security/form_login_setup.html
    
    access_control: 
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }